name: upday_task
description: Upday Task Project

version: 0.0.1+0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.3
  flutter_i18n: ^0.7.0
  intl: ^0.15.7
  shimmer: ^1.0.1
  rxdart: ^0.22.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  transparent_image: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flutter_i18n/
    - assets/images/upday_logo.png
    - assets/images/shutter_stock.png
    - test_resources/gallery_data_dummy.json

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Black.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
